### PR TITLE
add support for agg dsl in search and returning aggs in results

### PR DESCRIPTION
**Pull request by benedictfischer09**
https://www.pivotaltracker.com/story/show/111445274

### CODE REVIEW

**Comment by benedictfischer09** [comment]
@brupm @jeyb @divoxx

**Comment by brupm** [comment]
:100:

**Comment by jeyb** [comment]
:+1:

**Comment by divoxx** [comment]
:+1:

**Comment by benedictfischer09** [comment]
QA won't directly test this ticket so should I leave this open until https://github.com/doximity/doximity/pull/12859 is tested or merge now? I don't see tire being used in DocNav, Finder, or CC but Doximity just goes off master branch so as soon as I merge all future deploys will get this code which should be fine since the change is backwards compatible

**Comment by jeyb** [comment]
Keep it open until the Doximity PR is above to me merged. Then merge and point to latest master in Doximity PR.

**Comment by swangdox** [comment]
Verified in QA. Ready to deploy.

**Pull request merged**
